### ISSUE TITLE
Please add final code example

### ISSUE THREAD

**Issue by edo9k** [jamesroutley/write-a-hash-table#36]
I am not experienced C coder, and the lack of full code examples makes it really hard to check whether I am making a mistake or you guys simply did not provide the needed to code, or the direction that I should implement that part myself.

**Comment by raidan00** [comment]
https://github.com/jamesroutley/algorithms-and-data-structures/tree/master/hash-table/src

**Comment by jairajsahgal** [comment]
How do I compile the code?

**Comment by 0xekez** [comment]
@jairajsahgal You'll need to link everything together with your compilation command. When the executable is run, whatever is in `int main` in `main.c` will be run. Here is the command that I am using to compile the code:

```
cc src/main.c src/hash_table.c src/prime.c -o ht
```

This will produce an executable called `ht` which you can run.
