### ISSUE TITLE
Missing parenthesis in pseudocode hash

### ISSUE THREAD

**Issue by balasuar** [jamesroutley/write-a-hash-table#7]
`(a ** string_len - (i+1)) * char_code(string[i])`

is evaluated as `(i+1)` less than `a` to the power of `string_len`, due to the order of operations of arithmetic.

It would be clearer if you rewrote the pseudo code as:

`(a ** (string_len - (i+1))) * char_code(string[i])`. I believe this makes is it clear that you are raising `a` to the sum of `-(i+1)` and `string_len`.

**Comment by jamesroutley** [comment]
Thanks for pointing this out @balasuar - a [PR](https://github.com/jamesroutley/write-a-hash-table/commit/75f18f86df56d0de00512dbde2de395d22591d74) from @medium-endian has fixed it. Thanks all!
